import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";

import React from "react";
import {
  Image,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import Svg, {
  Defs,
  LinearGradient,
  Path,
  Stop,
  Text as SvgText,
} from "react-native-svg";

/* MOCK DATA (later backend se aye ga) */
const solarChartData = [12, 15, 14, 10, 9, 12, 14, 11];
const solarChartLabels = ["13:00", "14:00", "15:00", "16:00", "17:00", "18:00"];

export default function EstimateSolarGenerationScreen() {
  return (
    <SafeAreaView style={styles.container}>
      {/* ✅ FIXED USER HEADER */}
      <View style={styles.userHeaderWrapper}>
        <View style={styles.userCard}>
          <View>
            <Text style={styles.greeting}>Hi User!</Text>
            <Text style={styles.date}>Monday, 15 Jan 2026</Text>
          </View>

          <View style={styles.headerRight}>
            <Text style={styles.time}>4:00 PM</Text>
            <Ionicons name="partly-sunny" size={18} color="#f7b500" />
          </View>
        </View>
      </View>

      {/* ✅ SCROLLABLE CONTENT */}
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingBottom: 120 }}
      >
        {/* SUMMARY */}
        <View style={styles.summaryCard}>
          <View style={styles.summaryTop}>
            <View style={styles.kwhBadge}>
              <Ionicons name="flash" size={16} color="#2e7d32" />
              <Text style={styles.kwhText}>18.57 kWh</Text>
            </View>
            <Text style={styles.percentText}>30%</Text>
          </View>

          <Text style={styles.summaryText}>
            Estimated Solar generation this hour
          </Text>

          <View style={styles.progressBar}>
            <View style={styles.progressFill} />
          </View>
        </View>

        {/* STATS */}
        <View style={styles.grid}>
          <StatCard
            title="Solar generation"
            value="18.5"
            unit="kWh"
            image={require("../assets/images/estimated.png")}
          />
          <StatCard
            title="Estimated consumption"
            value="21.2"
            unit="kWh"
            image={require("../assets/images/estimated.png")}
          />
          <StatCard
            title="Solar coverage"
            value="70.0"
            unit="%"
            image={require("../assets/images/solarcoverage.png")}
          />
          <StatCard
            title="Grid dependency"
            value="30.0"
            unit="%"
            image={require("../assets/images/grid dependency.png")}
          />
        </View>

        {/* GRAPH */}
        <View style={styles.chartCard}>
          <Text style={styles.chartTitle}>Electricity generated by solar</Text>
          <Text style={styles.chartValue}>18.65 kWh</Text>
          <SolarChart data={solarChartData} labels={solarChartLabels} />
        </View>
      </ScrollView>

      {/* BOTTOM BAR */}
      <View style={styles.bottomBar}>
        <BottomIcon icon="home" onPress={() => router.push("/")} active />
        <BottomIcon icon="stats-chart" onPress={() => router.push("/stats")} />
        <BottomIcon icon="time" onPress={() => router.push("/history")} />
        <BottomIcon icon="person" onPress={() => router.push("/profile")} />
      </View>
    </SafeAreaView>
  );
}

/* ---------- COMPONENTS ---------- */

function StatCard({ title, value, unit, image }: any) {
  return (
    <View style={styles.statCard}>
      <View style={styles.iconCircle}>
        <Image source={image} style={styles.statImage} resizeMode="contain" />
      </View>

      <Text style={styles.cardTitle}>{title}</Text>
      <Text style={styles.cardValue}>
        {value} <Text style={styles.cardUnit}>{unit}</Text>
      </Text>
    </View>
  );
}

function BottomIcon({ icon, onPress, active }: any) {
  return (
    <Pressable onPress={onPress} style={styles.bottomIcon}>
      <Ionicons name={icon} size={24} color={active ? "#4caf50" : "#999"} />
    </Pressable>
  );
}

/* ---------- SOLAR CHART (WITH TOOLTIP + GRID) ---------- */

function SolarChart({ data, labels }: { data: number[]; labels: string[] }) {
  const [chartWidth, setChartWidth] = React.useState(0);

  const chartHeight = 160;
  const leftPadding = 44; // ✅ space for left numbers
  const bottomPadding = 28; // ✅ space for bottom numbers
  const topPadding = 12;
  const maxY = Math.max(...data, 0); // ✅ backend‑driven max value
  const steps = 4; // ✅ grid steps (0 → max)

  const currentIndex = 1;
  const currentValue = data[currentIndex];

  if (chartWidth === 0) {
    return (
      <View
        style={{ height: chartHeight + bottomPadding }}
        onLayout={(e) => setChartWidth(e.nativeEvent.layout.width)}
      />
    );
  }

  const stepX = (chartWidth - leftPadding) / (data.length - 1);

  const scaleY = (value: number) =>
    topPadding + chartHeight - (value / maxY) * chartHeight;

  const points = data.map((value, index) => ({
    x: leftPadding + index * stepX,
    y: scaleY(value),
  }));

  const linePath =
    `M ${points[0].x},${points[0].y} ` +
    points
      .slice(1)
      .map((p) => `L ${p.x},${p.y}`)
      .join(" ");

  const areaPath = `
    ${linePath}
    L ${chartWidth},${chartHeight + topPadding}
    L ${leftPadding},${chartHeight + topPadding}
    Z
  `;

  // ✅ Y‑axis values (dynamic, backend ready)
  const yAxisValues = Array.from({ length: steps + 1 }, (_, i) =>
    Math.round((maxY / steps) * (steps - i)),
  );

  return (
    <View>
      <Svg width={chartWidth} height={chartHeight + bottomPadding + topPadding}>
        <Defs>
          <LinearGradient id="grad" x1="0" y1="0" x2="0" y2="1">
            <Stop offset="0%" stopColor="#4caf50" stopOpacity="0.6" />
            <Stop offset="100%" stopColor="#4caf50" stopOpacity="0.1" />
          </LinearGradient>
        </Defs>

        {/* ✅ horizontal grid + LEFT numbers */}
        {yAxisValues.map((val, i) => {
          const y = scaleY(val);
          return (
            <React.Fragment key={i}>
              <Path
                d={`M ${leftPadding} ${y} L ${chartWidth} ${y}`}
                stroke="#ddd"
                strokeDasharray="4 4"
              />
              <SvgText
                x={leftPadding - 8}
                y={y + 4}
                fontSize="10"
                fill="#999"
                textAnchor="end"
              >
                {val}
              </SvgText>
            </React.Fragment>
          );
        })}

        {/* ✅ area + line */}
        <Path d={areaPath} fill="url(#grad)" />
        <Path d={linePath} stroke="#2e7d32" strokeWidth={2} fill="none" />

        {/* ✅ current vertical indicator */}
        <Path
          d={`M ${points[currentIndex].x} ${topPadding}
              L ${points[currentIndex].x} ${chartHeight + topPadding}`}
          stroke="#bbb"
          strokeDasharray="4 4"
        />
      </Svg>

      {/* ✅ tooltip */}
      <View
        style={[
          styles.tooltip,
          {
            left: points[currentIndex].x - 22,
            top: points[currentIndex].y - 36,
          },
        ]}
      >
        <Text style={styles.tooltipText}>{currentValue} kWh</Text>
      </View>

      {/* ✅ bottom labels (never overlap graph) */}
      <View style={[styles.graphLabels, { marginLeft: leftPadding }]}>
        {labels.map((label, i) => (
          <Text key={i} style={styles.graphLabelText}>
            {label}
          </Text>
        ))}
      </View>
    </View>
  );
}

/* ---------- STYLES ---------- */

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f6f8" },

  summaryTop: { flexDirection: "row", justifyContent: "space-between" },

  kwhBadge: {
    flexDirection: "row",
    gap: 6,
    backgroundColor: "#c8f0c2",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignItems: "center",
  },

  kwhText: { fontWeight: "700", color: "#2e7d32" },
  percentText: { color: "#e53935", fontWeight: "600" },

  summaryText: { color: "#777", marginVertical: 8 },

  progressBar: {
    height: 6,
    backgroundColor: "#e0e0e0",
    borderRadius: 6,
  },

  progressFill: {
    width: "30%",
    height: 6,
    backgroundColor: "#4caf50",
    borderRadius: 6,
  },

  grid: {
    padding: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },

  statCard: {
    width: "48%",
    backgroundColor: "#c8f0c2",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },

  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#e8f5e9",
    justifyContent: "center",
    alignItems: "center",
  },

  cardTitle: { marginTop: 8, color: "#2e7d32" },
  cardValue: { fontSize: 20, fontWeight: "700" },
  cardUnit: { fontSize: 12 },

  chartCard: {
    backgroundColor: "#fff",
    margin: 16,
    borderRadius: 16,
    padding: 16,
  },

  chartTitle: { color: "#777" },
  chartValue: { fontSize: 18, fontWeight: "700", marginBottom: 12 },

  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 70,
    backgroundColor: "#fff",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderTopWidth: 1,
    borderColor: "#eee",
  },

  bottomIcon: { alignItems: "center" },

  graphLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    marginTop: 4,
  },

  graphLabelText: {
    fontSize: 10,
    color: "#999",
  },

  tooltip: {
    position: "absolute",
    backgroundColor: "#000",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },

  tooltipText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "600",
  },
  statImage: {
    width: 22,
    height: 22,
    tintColor: "#2e7d32", // optional (remove if image colored hai)
  },
  userHeaderWrapper: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: "#f5f6f8",
    zIndex: 10,
  },

  userCard: {
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 14,

    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",

    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },

  greeting: {
    fontSize: 15,
    fontWeight: "600",
  },

  date: {
    fontSize: 11,
    color: "#888",
    marginTop: 2,
  },

  time: {
    fontSize: 13,
    fontWeight: "600",
  },

  headerRight: {
    alignItems: "center",
    gap: 2,
  },

  summaryCard: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: 12, // ✅ important
    borderRadius: 16,
    padding: 16,
  },
});
