//done
import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import React, { useEffect, useState } from "react";
import {
  Image,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import Svg, {
  Defs,
  LinearGradient,
  Path,
  Rect,
  Stop,
  Text as SvgText,
} from "react-native-svg";

const BACKEND_DATA = {
  userGreeting: "Hi User!",
  summaryKwh: "18.57",
  summaryPercent: "30%",
  solarGen: "18.5",
  estConsum: "21.2",
  solarCover: "70.0",
  gridDep: "30.0",
  chartTotal: "18.65",
  solarChartData: [12, 15, 14, 10, 9, 12, 14, 11],
  solarChartLabels: ["13:00", "14:00", "15:00", "16:00", "17:00", "18:00"],
};

export default function EstimateSolarGenerationScreen() {
  const [currentDateTime, setCurrentDateTime] = useState(new Date());

  useEffect(() => {
    const timer = setInterval(() => setCurrentDateTime(new Date()), 60000);
    return () => clearInterval(timer);
  }, []);

  const formattedDate = currentDateTime.toLocaleDateString("en-GB", {
    weekday: "long",
    day: "numeric",
    month: "short",
    year: "numeric",
  });
  const formattedTime = currentDateTime.toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.userHeaderWrapper}>
        <View style={styles.userCard}>
          <View>
            <Text style={styles.greeting}>{BACKEND_DATA.userGreeting}</Text>
            <Text style={styles.date}>{formattedDate}</Text>
          </View>

          <View style={styles.headerRight}>
            <Text style={styles.time}>{formattedTime}</Text>
            <Ionicons name="partly-sunny" size={18} color="#f7b500" />
          </View>
        </View>
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingBottom: 120 }}
      >
        {/* SUMMARY CARD */}
        <View style={styles.summaryCard}>
          <View style={styles.summaryTop}>
            <View style={styles.kwhBadge}>
              <Ionicons name="flash" size={16} color="#2e7d32" />
              <Text style={styles.kwhText}>{BACKEND_DATA.summaryKwh} kWh</Text>
            </View>
            <Text style={styles.percentText}>
              {BACKEND_DATA.summaryPercent}
            </Text>
          </View>
          <Text style={styles.summaryText}>
            Estimated Solar generation this hour
          </Text>
          <View style={styles.progressBar}>
            <View
              style={[
                styles.progressFill,
                { width: `${parseFloat(BACKEND_DATA.summaryPercent)}%` },
              ]}
            />
          </View>
        </View>

        {/* STATS GRID */}
        <View style={styles.grid}>
          <StatCard
            title="Solar generation"
            value={BACKEND_DATA.solarGen}
            unit="kWh"
            image={require("../assets/images/lamp.png")}
          />
          <StatCard
            title="Estimated consumption"
            value={BACKEND_DATA.estConsum}
            unit="kWh"
            image={require("../assets/images/estimated.png")}
          />
          <StatCard
            title="Solar coverage"
            value={BACKEND_DATA.solarCover}
            unit="%"
            image={require("../assets/images/solarcoverage.png")}
          />
          <StatCard
            title="Grid dependency"
            value={BACKEND_DATA.gridDep}
            unit="%"
            image={require("../assets/images/grid dependency.png")}
          />
        </View>

        {/* GRAPH CARD */}
        <View style={styles.chartCard}>
          <Text style={styles.chartTitle}>Electricity generated by solar</Text>
          <Text style={styles.chartValue}>{BACKEND_DATA.chartTotal} kWh</Text>
          <SolarChart
            data={BACKEND_DATA.solarChartData}
            labels={BACKEND_DATA.solarChartLabels}
          />
        </View>
      </ScrollView>

      {/* ✅ UPDATED BOTTOM BAR */}
      <View style={styles.bottomBar}>
        <BottomIcon
          imageSource={require("../assets/images/home.png")}
          onPress={() => router.push("/estimatesolar-generation")}
          active={true} // Home page par active
        />
        <BottomIcon
          imageSource={require("../assets/images/bar-chart.png")}
          onPress={() => router.push("/stats")}
          active={false}
        />
        <BottomIcon
          imageSource={require("../assets/images/clock.png")}
          onPress={() => router.push("/usage")}
          active={false}
        />
        <BottomIcon
          imageSource={require("../assets/images/user.png")}
          onPress={() => router.push("/profile")}
          active={false}
        />
      </View>
    </SafeAreaView>
  );
}

/* ---------- COMPONENTS ---------- */

function StatCard({ title, value, unit, image }: any) {
  return (
    <View style={styles.statCard}>
      <View style={styles.iconCircle}>
        <Image source={image} style={styles.statImage} resizeMode="contain" />
      </View>
      <Text style={styles.cardTitle}>{title}</Text>
      <Text style={styles.cardValue}>
        {value} <Text style={styles.cardUnit}>{unit}</Text>
      </Text>
    </View>
  );
}

// ✅ UPDATED BOTTOM ICON COMPONENT
function BottomIcon({ imageSource, onPress, active }: any) {
  return (
    <Pressable onPress={onPress} style={styles.bottomIconContainer}>
      {active && <View style={styles.activeIndicator} />}
      <Image
        source={imageSource}
        style={[
          styles.bottomIconImage,
          { tintColor: active ? "#4caf50" : "#999" },
        ]}
        resizeMode="contain"
      />
    </Pressable>
  );
}

function SolarChart({ data, labels }: { data: number[]; labels: string[] }) {
  const [chartWidth, setChartWidth] = React.useState(0);
  const chartHeight = 160;
  const leftPadding = 45;
  const bottomPadding = 28;
  const topPadding = 35;
  const maxY = Math.max(...data, 10);
  const steps = 4;
  const activeIndex = 3;

  if (chartWidth === 0) {
    return (
      <View
        style={{ height: chartHeight + bottomPadding + topPadding }}
        onLayout={(e) => setChartWidth(e.nativeEvent.layout.width)}
      />
    );
  }

  const stepX = (chartWidth - leftPadding) / (data.length - 1);
  const scaleY = (value: number) =>
    topPadding + chartHeight - (value / maxY) * chartHeight;

  const points = data.map((value, index) => ({
    x: leftPadding + index * stepX,
    y: scaleY(value),
  }));

  const linePath =
    `M ${points[0].x},${points[0].y} ` +
    points
      .slice(1)
      .map((p) => `L ${p.x},${p.y}`)
      .join(" ");
  const areaPath = `${linePath} L ${chartWidth},${chartHeight + topPadding} L ${leftPadding},${chartHeight + topPadding} Z`;
  const yAxisValues = Array.from({ length: steps + 1 }, (_, i) =>
    Math.round((maxY / steps) * (steps - i)),
  );
  const activePoint = points[activeIndex];
  const activeValue = data[activeIndex];

  return (
    <View>
      <Svg width={chartWidth} height={chartHeight + bottomPadding + topPadding}>
        <Defs>
          <LinearGradient id="grad" x1="0" y1="0" x2="0" y2="1">
            <Stop offset="0%" stopColor="#4caf50" stopOpacity="0.4" />
            <Stop offset="100%" stopColor="#4caf50" stopOpacity="0.01" />
          </LinearGradient>
        </Defs>

        {yAxisValues.map((val, i) => {
          const y = scaleY(val);
          return (
            <React.Fragment key={i}>
              <Path
                d={`M ${leftPadding} ${y} L ${chartWidth} ${y}`}
                stroke="#eee"
                strokeDasharray={i === steps ? "0" : "4,4"}
              />
              <SvgText
                x={leftPadding - 10}
                y={y + 5}
                fontSize="12"
                fontWeight="600"
                fill="#999"
                textAnchor="end"
              >
                {val}
              </SvgText>
            </React.Fragment>
          );
        })}

        <Path d={areaPath} fill="url(#grad)" />
        <Path d={linePath} stroke="#2e7d32" strokeWidth={2} fill="none" />
        <Path
          d={`M ${activePoint.x} ${topPadding} L ${activePoint.x} ${chartHeight + topPadding}`}
          stroke="#000"
          strokeWidth="1"
          strokeDasharray="4,4"
        />
        <Path
          d={`M ${leftPadding} ${activePoint.y} L ${chartWidth} ${activePoint.y}`}
          stroke="#ccc"
          strokeWidth="1"
          strokeDasharray="4,4"
        />

        <Rect
          x={activePoint.x - 40}
          y={activePoint.y - 35}
          width={80}
          height={22}
          fill="#000"
          rx={5}
        />
        <SvgText
          x={activePoint.x}
          y={activePoint.y - 19}
          fontSize="11"
          fontWeight="bold"
          fill="#fff"
          textAnchor="middle"
        >
          {activeValue} kWh
        </SvgText>
        <Path
          d={`M ${activePoint.x - 4} ${activePoint.y} a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0`}
          fill="#000"
          stroke="#fff"
          strokeWidth="2"
        />
      </Svg>

      <View style={[styles.graphLabels, { marginLeft: leftPadding }]}>
        {labels.map((label, i) => (
          <Text
            key={i}
            style={[
              styles.graphLabelText,
              i === activeIndex && { color: "#000", fontWeight: "bold" },
            ]}
          >
            {label}
          </Text>
        ))}
      </View>
    </View>
  );
}

/* ---------- STYLES ---------- */
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f6f8" },
  userHeaderWrapper: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 8 },
  userCard: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 4,
  },
  greeting: { fontSize: 16, fontWeight: "700" },
  date: { fontSize: 12, color: "#888", marginTop: 2 },
  time: { fontSize: 14, fontWeight: "700" },
  headerRight: { alignItems: "center" },
  summaryCard: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 16,
    padding: 16,
  },
  summaryTop: { flexDirection: "row", justifyContent: "space-between" },
  kwhBadge: {
    flexDirection: "row",
    gap: 6,
    backgroundColor: "#e8f5e9",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignItems: "center",
  },
  kwhText: { fontWeight: "700", color: "#2e7d32" },
  percentText: { color: "#e53935", fontWeight: "600" },
  summaryText: { color: "#777", marginVertical: 8 },
  progressBar: { height: 6, backgroundColor: "#e0e0e0", borderRadius: 6 },
  progressFill: { height: 6, backgroundColor: "#4caf50", borderRadius: 6 },
  grid: {
    padding: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  statCard: {
    width: "48%",
    backgroundColor: "#e8f5e9",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  cardTitle: { marginTop: 8, color: "#2e7d32", fontSize: 12 },
  cardValue: { fontSize: 18, fontWeight: "700" },
  cardUnit: { fontSize: 12 },
  chartCard: {
    backgroundColor: "#fff",
    margin: 16,
    borderRadius: 16,
    padding: 16,
  },
  chartTitle: { color: "#777" },
  chartValue: { fontSize: 18, fontWeight: "700", marginBottom: 12 },

  // ✅ STYLES FOR UPDATED BOTTOM BAR
  bottomBar: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: 70,
    backgroundColor: "#fff",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderTopWidth: 1,
    borderColor: "#eee",
  },
  bottomIconContainer: {
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    width: 60,
  },
  bottomIconImage: {
    width: 24,
    height: 24,
  },
  activeIndicator: {
    position: "absolute",
    top: 0,
    width: 35,
    height: 3,
    backgroundColor: "#4caf50",
    borderRadius: 2,
  },
  graphLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  graphLabelText: { fontSize: 10, color: "#999" },
  statImage: { width: 22, height: 22 },
});
